lligaproject/lliga/urls.py
from django.urls import path

from . import views

# si no posem app_name no funcionen el links
# les urls dels links les fem a partir de polls:name
app_name = "lliga"

urlpatterns = [
    path("", views.IndexView, name="index"),
    path("menu", views.MenuView, name="menu"), 
    path("<int:lliga_id>/classificacio", views.ClassificacioView, name="classificacio"),    
]

lligaproject/lligaproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("lliga/", include("lliga.urls")),  
    path('admin/', admin.site.urls),
]

lligaproject/lliga/models.py
from django.db import models

class Lliga(models.Model):
    nom = models.CharField(max_length=255)
    pais = models.CharField(max_length=255)
    temporada = models.CharField(max_length=255)
    data_inici = models.DateField()
    data_final = models.DateField()    

    def __str__(self):
        return f"{self.nom} {self.temporada}" 

    def numero_equips(self):
        return self.equips.count()

class Equip(models.Model):
    nom = models.CharField(max_length=255)
    ciutat = models.CharField(max_length=255)
    estadi = models.CharField(max_length=255)
    entrenador = models.CharField(max_length=255)
    any_fundacio = models.IntegerField()
    lliga = models.ForeignKey(Lliga, on_delete=models.CASCADE, related_name='equips')

    def __str__(self):
        return self.nom

class Jugador(models.Model):
    nom = models.CharField(max_length=255)
    posicio = models.CharField(max_length=255)
    edat = models.IntegerField()
    nacionalitat = models.CharField(max_length=255)
    equip = models.ForeignKey(Equip, on_delete=models.CASCADE, related_name='jugadors')

    def __str__(self):
        return self.nom

class Partit(models.Model):
    class Meta:
        unique_together = ["local","visitant","lliga"]
    local = models.ForeignKey(Equip,on_delete=models.CASCADE,
                    related_name="partits_local")
    visitant = models.ForeignKey(Equip,on_delete=models.CASCADE,
                    related_name="partits_visitant")
    lliga = models.ForeignKey(Lliga,on_delete=models.CASCADE)
    detalls = models.TextField(null=True,blank=True)
    inici = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return "{} - {}".format(self.local,self.visitant)

    def gols_local(self):
        return self.event_set.filter(
            tipus=Event.EventType.GOL,equip=self.local).count()

    def gols_visitant(self):
        return self.event_set.filter(
            tipus=Event.EventType.GOL,equip=self.visitant).count()

class Event(models.Model):
    # el tipus d'event l'implementem amb algo tipus "enum"
    class EventType(models.TextChoices):
        GOL = "GOL"
        AUTOGOL = "AUTOGOL"
        FALTA = "FALTA"
        PENALTY = "PENALTY"
        MANS = "MANS"
        CESSIO = "CESSIO"
        FORA_DE_JOC = "FORA_DE_JOC"
        ASSISTENCIA = "ASSISTENCIA"
        TARGETA_GROGA = "TARGETA_GROGA"
        TARGETA_VERMELLA = "TARGETA_VERMELLA"
    partit = models.ForeignKey(Partit,on_delete=models.CASCADE)
    temps = models.TimeField()
    tipus = models.CharField(max_length=30,choices=EventType.choices)
    jugador = models.ForeignKey(Jugador,null=True,
                    on_delete=models.SET_NULL,
                    related_name="events_fets")
    equip = models.ForeignKey(Equip,null=True,
                    on_delete=models.SET_NULL)
    # per les faltes
    jugador2 = models.ForeignKey(Jugador,null=True,blank=True,
                    on_delete=models.SET_NULL,
                    related_name="events_rebuts")
    detalls = models.TextField(null=True,blank=True)


    def __str__(self):
        return f"{self.tipus} - {self.partit} - {self.jugador}"

lligaproject/lliga/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django import forms
from django.shortcuts import redirect

from .models import *

def IndexView(request):
    ctx_lligues = Lliga.objects.all()

    return render(request,"lliga/index.html",
                {
                    "ctx_lligues":ctx_lligues,
                })    

def ClassificacioView(request,lliga_id):
    try:
        lliga = Lliga.objects.get(pk=lliga_id)
        equips = lliga.equips.all()
        ctx_classificacio = []
    
        # calculem punts en llista de tuples (equip,punts)
        for equip in equips:
            punts = 0
            for partit in lliga.partit_set.filter(local=equip):
                if partit.gols_local() > partit.gols_visitant():
                    punts += 3
                elif partit.gols_local() == partit.gols_visitant():
                    punts += 1
            for partit in lliga.partit_set.filter(visitant=equip):
                if partit.gols_local() < partit.gols_visitant():
                    punts += 3
                elif partit.gols_local() == partit.gols_visitant():
                    punts += 1
            ctx_classificacio.append( (punts,equip.nom) )
        # ordenem llista
        ctx_classificacio.sort(reverse=True)
    except LLiga.DoesNotExist:
        raise Http404("La lliga not existeix")

    return render(request,"lliga/classificacio.html",
                {
                    "ctx_classificacio":ctx_classificacio,
                })

class MenuForm(forms.Form):
    lliga = forms.ModelChoiceField(queryset=Lliga.objects.all())
 
def MenuView(request):
    form = MenuForm()
    if request.method == "POST":
        form = MenuForm(request.POST)
        if form.is_valid():
            lliga = form.cleaned_data.get("lliga")
            # cridem a /classificacio/<lliga_id>
            return redirect('lliga:classificacio', lliga.id)
    return render(request, "lliga/menu.html",{
                    "form": form,
            }) 

lligaproject/lliga/templates/lliga/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lliga/style.css' %}">    

    <title>LLIGA app</title>

</head>
<body>

    <div class="header">   
        {% block title %}
        <div class="titol">LLIGA app</div>        
        {% endblock title %}         

    </div>

    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>

    <div class="footer">
        {% block header %}
        (c) XTEC 2024
        {% endblock header %}
    </div>

</body>
</html>

lligaproject/lliga/templates/lliga/classificacio.html
{% extends "lliga/base.html" %}

{% block title %}<div class="titol">Classificació</div>  {% endblock title %}

{% block content %}

    {% if ctx_classificacio %}
        <ol>
        {% for equip in ctx_classificacio %}
            <li>{{equip.1}} ({{equip.0}} punts)</li>
        {% endfor %}
        </ol>
    {% else %}
        <p>No objects are available.</p>
    {% endif %}

    <div>
        <p>
            <a href="{% url 'lliga:index' %}">Return to Index</a>
        </p>    
    </div>  

{% endblock %}

lligaproject/lliga/templates/lliga/index.html
{% extends "lliga/base.html" %}

{% block content %}

    {% if ctx_lligues %}
        <ul>
        {% for lliga in ctx_lligues %}
        <li><a href="{% url 'lliga:classificacio' lliga.id %}">{{ lliga }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No objects are available.</p>
    {% endif %}

{% endblock %}

lligaproject/lliga/templates/lliga/menu.html
{% extends "lliga/base.html" %}

{% block content %}

    <h1>Menu Lligues</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    
        <input type="submit" name="submit">
    </form>

{% endblock %}






 